repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^catface/template/.*$
      - id: ruff-format
        exclude: ^catface/template/.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^catface/template/.*$
      - id: end-of-file-fixer
        exclude: ^catface/template/.*$
      - id: check-yaml
        exclude: ^catface/template/.*$
      - id: check-added-large-files
        exclude: ^catface/template/.*$
      - id: check-toml

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
        exclude: ^catface/template/.*$
